Tests_ayush
Nikhil31Lathiya/oza-lab pull request #8
Opened 2023-02-09 11:47 UTC by Ayush765

2023-02-09 12:44 UTC, RutuThakkar510 commented on src/services/patient/create_patient.js
> +    const {BAD_REQUEST,OK}= StatusCodes;
please remove this and use codes instead.
200 = OK
400 = BAD_REQUEST

2023-02-09 12:44 UTC, RutuThakkar510 commented on src/services/tests/create_test.js
> +  const { BAD_REQUEST, OK } = StatusCodes;
same as above.

2023-02-10 05:58 UTC, rututhakkar10 commented on src/services/patient/delete_patient.js
> +    const patient = await patientRepository.deletePatient(parseInt(req.params.id));
before deleting patient we need to check whether he/she exist or not.
so before deleting the patient get patient by Id if it exist then only delete the patient otherwise return error message: No patient found.

2023-02-10 05:59 UTC, rututhakkar10 commented on src/services/tests/delete_test.js
> +  const test = await testRepository.deleteTest(parseInt(req.params.id));
same as above.
need to get test before delete

2023-02-10 06:10 UTC, Ayush765 commented on src/services/tests/delete_test.js
> +  const test = await testRepository.deleteTest(parseInt(req.params.id));
ok

2023-02-10 07:08 UTC, rututhakkar10 requested changes
@Ayush765 please resolve the conflicts

2023-02-14 11:27 UTC, rututhakkar10 approved these changes
looks good to me.

2023-02-14 11:27 UTC, merged